<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20260106113656 extends AbstractMigration
{
    public function up(Schema $schema): void
    {
        $this->addSql('CREATE TABLE food_intake (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, date DATE NOT NULL, amount INT NOT NULL, type VARCHAR(255) NOT NULL, food_id INT NOT NULL, user_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_EE8CEDD9BA8E87C4 ON food_intake (food_id)');
        $this->addSql('CREATE INDEX IDX_EE8CEDD9A76ED395 ON food_intake (user_id)');
        $this->addSql('ALTER TABLE food_intake ADD CONSTRAINT FK_EE8CEDD9BA8E87C4 FOREIGN KEY (food_id) REFERENCES food (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE food_intake ADD CONSTRAINT FK_EE8CEDD9A76ED395 FOREIGN KEY (user_id) REFERENCES "user" (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE exercise_session ALTER exercise_id SET NOT NULL');
        $this->addSql('ALTER TABLE exercise_session ALTER user_id SET NOT NULL');
        $this->addSql('ALTER TABLE food ALTER description SET NOT NULL');
        $this->addSql('ALTER TABLE heart_parameters ALTER user_id SET NOT NULL');
        $this->addSql('ALTER TABLE medication_schedule ALTER medicine_id SET NOT NULL');
        $this->addSql('ALTER TABLE medication_schedule ALTER user_id SET NOT NULL');
        $this->addSql('ALTER TABLE "user" ALTER date_of_birth TYPE DATE');
        $this->addSql('ALTER TABLE weight_parameters ALTER user_id SET NOT NULL');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('ALTER TABLE food_intake DROP CONSTRAINT FK_EE8CEDD9BA8E87C4');
        $this->addSql('ALTER TABLE food_intake DROP CONSTRAINT FK_EE8CEDD9A76ED395');
        $this->addSql('DROP TABLE food_intake');
        $this->addSql('ALTER TABLE exercise_session ALTER exercise_id DROP NOT NULL');
        $this->addSql('ALTER TABLE exercise_session ALTER user_id DROP NOT NULL');
        $this->addSql('ALTER TABLE food ALTER description DROP NOT NULL');
        $this->addSql('ALTER TABLE heart_parameters ALTER user_id DROP NOT NULL');
        $this->addSql('ALTER TABLE medication_schedule ALTER medicine_id DROP NOT NULL');
        $this->addSql('ALTER TABLE medication_schedule ALTER user_id DROP NOT NULL');
        $this->addSql('ALTER TABLE "user" ALTER date_of_birth TYPE TIMESTAMP(0) WITHOUT TIME ZONE');
        $this->addSql('ALTER TABLE weight_parameters ALTER user_id DROP NOT NULL');
    }
}
