<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20260104155554 extends AbstractMigration
{
    public function up(Schema $schema): void
    {
        $this->addSql('CREATE TABLE medication_schedule (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, time_of_day VARCHAR(255) NOT NULL, medicine_id INT DEFAULT NULL, user_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_729D8E052F7D140A ON medication_schedule (medicine_id)');
        $this->addSql('CREATE INDEX IDX_729D8E05A76ED395 ON medication_schedule (user_id)');
        $this->addSql('ALTER TABLE medication_schedule ADD CONSTRAINT FK_729D8E052F7D140A FOREIGN KEY (medicine_id) REFERENCES medicine (id)');
        $this->addSql('ALTER TABLE medication_schedule ADD CONSTRAINT FK_729D8E05A76ED395 FOREIGN KEY (user_id) REFERENCES "user" (id)');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('ALTER TABLE medication_schedule DROP CONSTRAINT FK_729D8E052F7D140A');
        $this->addSql('ALTER TABLE medication_schedule DROP CONSTRAINT FK_729D8E05A76ED395');
        $this->addSql('DROP TABLE medication_schedule');
    }
}
