<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260103180254 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE exercise_session (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, duration INT NOT NULL, performed_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, exercise_id INT DEFAULT NULL, user_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_A512291E934951A ON exercise_session (exercise_id)');
        $this->addSql('CREATE INDEX IDX_A512291A76ED395 ON exercise_session (user_id)');
        $this->addSql('ALTER TABLE exercise_session ADD CONSTRAINT FK_A512291E934951A FOREIGN KEY (exercise_id) REFERENCES exercise (id)');
        $this->addSql('ALTER TABLE exercise_session ADD CONSTRAINT FK_A512291A76ED395 FOREIGN KEY (user_id) REFERENCES "user" (id)');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE exercise_session DROP CONSTRAINT FK_A512291E934951A');
        $this->addSql('ALTER TABLE exercise_session DROP CONSTRAINT FK_A512291A76ED395');
        $this->addSql('DROP TABLE exercise_session');
    }
}
