<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20251227182858 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE exercise (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, duration INT NOT NULL, date TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, "default" BOOLEAN NOT NULL, user_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_AEDAD51CA76ED395 ON exercise (user_id)');
        $this->addSql('CREATE TABLE weight_parameters (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, real_weight INT NOT NULL, date TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, user_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_6E6EDEA3A76ED395 ON weight_parameters (user_id)');
        $this->addSql('ALTER TABLE exercise ADD CONSTRAINT FK_AEDAD51CA76ED395 FOREIGN KEY (user_id) REFERENCES "user" (id)');
        $this->addSql('ALTER TABLE weight_parameters ADD CONSTRAINT FK_6E6EDEA3A76ED395 FOREIGN KEY (user_id) REFERENCES "user" (id)');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE exercise DROP CONSTRAINT FK_AEDAD51CA76ED395');
        $this->addSql('ALTER TABLE weight_parameters DROP CONSTRAINT FK_6E6EDEA3A76ED395');
        $this->addSql('DROP TABLE exercise');
        $this->addSql('DROP TABLE weight_parameters');
    }
}
