<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20260106094957 extends AbstractMigration
{
    public function up(Schema $schema): void
    {
        $this->addSql('CREATE TABLE food (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(255) NOT NULL, description VARCHAR(255) NULL, proteins INT NOT NULL, carbohydrates INT NOT NULL, fats INT NOT NULL, calories INT NOT NULL, system BOOLEAN NOT NULL, brand_id INT NOT NULL, category_id INT NOT NULL, user_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_D43829F744F5D008 ON food (brand_id)');
        $this->addSql('CREATE INDEX IDX_D43829F712469DE2 ON food (category_id)');
        $this->addSql('CREATE INDEX IDX_D43829F7A76ED395 ON food (user_id)');
        $this->addSql('ALTER TABLE food ADD CONSTRAINT FK_D43829F744F5D008 FOREIGN KEY (brand_id) REFERENCES brand (id)');
        $this->addSql('ALTER TABLE food ADD CONSTRAINT FK_D43829F712469DE2 FOREIGN KEY (category_id) REFERENCES category (id)');
        $this->addSql('ALTER TABLE food ADD CONSTRAINT FK_D43829F7A76ED395 FOREIGN KEY (user_id) REFERENCES "user" (id) NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('ALTER TABLE food DROP CONSTRAINT FK_D43829F744F5D008');
        $this->addSql('ALTER TABLE food DROP CONSTRAINT FK_D43829F712469DE2');
        $this->addSql('ALTER TABLE food DROP CONSTRAINT FK_D43829F7A76ED395');
        $this->addSql('DROP TABLE food');
    }
}
