<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20251227153538 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE heart_parameters (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, arm VARCHAR(255) NOT NULL, heart_beat INT NOT NULL, systola INT NOT NULL, diastola INT NOT NULL, date TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, user_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_3539B684A76ED395 ON heart_parameters (user_id)');
        $this->addSql('ALTER TABLE heart_parameters ADD CONSTRAINT FK_3539B684A76ED395 FOREIGN KEY (user_id) REFERENCES "user" (id)');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE heart_parameters DROP CONSTRAINT FK_3539B684A76ED395');
        $this->addSql('DROP TABLE heart_parameters');
    }
}
